### ISSUE TITLE
Redirected output starts response headers on same line as request body

### ISSUE THREAD

**Issue by hughpv** [httpie/httpie#1006]
When I run a POST request without redirection, I see the response headers start on a new line:

```
            }
        }
    }
}

HTTP/1.1 201
Date: Mon, 21 Dec 2020 13:39:00 GMT
Content-Length: 0
```

But when I redirect the output, I see the `HTTP/1.1 201` on the same line as the request:

```
            }
        }
    }
}HTTP/1.1 201 
Date: Mon, 21 Dec 2020 13:36:09 GMT
Content-Length: 0
```

The options I specified in each case were `http -v --pretty format --unsorted`; the only difference was in the second case I redirected the output to a file.

**Comment by jakubroztocil** [comment]
Thanks for the report. This is a bug indeed.


```bash
$ http -v httpbin.org/post a=b | cat
```

```http
POST /post HTTP/1.1
Host: httpbin.org

{"a": "b"}HTTP/1.1 200 OK
         ^
```

**Comment by sebastianczech** [comment]
I was looking at this issue - after small analysis I found in file [writer.py](https://github.com/httpie/httpie/blob/master/httpie/output/writer.py) code which is responsible for inserting `\n\n` only for terminal output only (line 110):
```
    if (env.stdout_isatty and with_body
            and not getattr(requests_message, 'is_body_upload_chunk', False)):
```

If we remove `env.stdout_isatty and` and leave the rest as it is e.g:

```
    if (with_body
            and not getattr(requests_message, 'is_body_upload_chunk', False)):
```
`test_verbose_redirected_stdout_separator` in `test_regressions.py` will work, but many other tests will stop working. Is it intentional behaviour, that only for terminal output only (not redirects to file or piping) there will be additional `\n\n` ? If yes, then it's not a bug, If not, is it ok to not to check `env.stdout_isatty` and put `\n\n` also for redirects or piping ?

**Comment by Almad** [comment]
This was added when streaming support was added in https://github.com/httpie/httpie/commit/6925d930dac343140cce52631e74862c5412f783 — I'd maybe wait for @jakubroztocil to confirm whether adding the `\n\n` wouldn't break features in streaming

**Comment by jakubroztocil** [comment]
@sebastianczech Those are relevant bits indeed. There are quite a few scenarios that need to be handled. What has made things even more complicated, and has introduced this bug, is the new support for streamed uploads with simultaneous terminal output. I’m looking into fixing this, starting with ensuring we have tests for all the scenarios. Will publish soon.

**Comment by jakubroztocil** [comment]
HTTPie 2.4.0 fixing the incorrect formatting has just been released 🥧
