### ISSUE TITLE
HTTPie doesn't apply type checking to the top-level lists

### ISSUE THREAD

**Issue by ducaale** [httpie/httpie#1286]
## Checklist

- [x] I've searched for similar issues.
- [x] I'm using the latest version of HTTPie.

---

## Minimal reproduction code and steps

```bash
http httpbin.org/post '[1]=1' '[2]=2' x=5 --offline
```

## Current result

```bash
POST /post HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 32
Content-Type: application/json
Host: httpbin.org
User-Agent: HTTPie/3.0.0

{
    "": [
        null,
        "1",
        "2"
    ],
    "x": "5"
}
```

## Expected result

```bash
HTTPie Type Error: Can't perform 'key' based access on '' which has a type of 'array' but this operation requires a type of 'object'.
```

---

## Debug output

Please re-run the command with `--debug`, then copy the entire command & output and paste both below:

```bash
$ http httpbin.org/post '[1]=1' '[2]=2' x=5 --offline --debug
HTTPie 3.0.0
Requests 2.22.0
Pygments 2.7.2
Python 3.8.5 (default, May 27 2021, 13:30:53)
[GCC 9.3.0]
/usr/bin/python3
Linux 5.10.81.1-microsoft-standard-WSL2

<Environment {'as_silent': <function Environment.as_silent at 0x7ff7f371c550>,
 'colors': 256,
 'config': {'default_options': []},
 'config_dir': PosixPath('/home/ducaale/.httpie'),
 'devnull': <property object at 0x7ff7f3af47c0>,
 'is_windows': False,
 'log_error': <function Environment.log_error at 0x7ff7f371c5e0>,
 'program_name': 'http',
 'stderr': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'stderr_isatty': True,
 'stdin': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>,
 'stdin_encoding': 'utf-8',
 'stdin_isatty': True,
 'stdout': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>,
 'stdout_encoding': 'utf-8',
 'stdout_isatty': True}>

<PluginManager {'adapters': [],
 'auth': [<class 'httpie.plugins.builtin.BasicAuthPlugin'>,
          <class 'httpie.plugins.builtin.DigestAuthPlugin'>,
          <class 'httpie.plugins.builtin.BearerAuthPlugin'>],
 'converters': [],
 'formatters': [<class 'httpie.output.formatters.headers.HeadersFormatter'>,
                <class 'httpie.output.formatters.json.JSONFormatter'>,
                <class 'httpie.output.formatters.xml.XMLFormatter'>,
                <class 'httpie.output.formatters.colors.ColorFormatter'>]}>

>>> requests.request(**{'auth': None,
 'data': b'{"": [null, "1", "2"], "x": "5"}',
 'headers': <HTTPHeadersDict('User-Agent': b'HTTPie/3.0.0', 'Accept': b'application/json, */*;q=0.5', 'Content-Type': b'application/json')>,
 'method': 'post',
 'params': <generator object MultiValueOrderedDict.items at 0x7ff7f337c7b0>,
 'url': 'http://httpbin.org/post'})

POST /post HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 32
Content-Type: application/json
Host: httpbin.org
User-Agent: HTTPie/3.0.0

{
    "": [
        null,
        "1",
        "2"
    ],
    "x": "5"
}
```

## Additional information, screenshots, or code examples

N/A

**Comment by isidentical** [comment]
I don't think we have documented the top-level list functionality, so we probably need to discuss it from a few aspects.

Current implementation ensures these conditions and then if all checks out, it promotes the the value to a standalone object:
- Is the resulted object has only one key?
- Is the only present key an empty string?
- Is the value for that key is a list?

```python
{
    "": [...]
}

=>

[...]
```

Other objects, even if they have an empty string key with a list stay the same.
```python
{
    "": [...],
    ...: ...
}

=>

{
    "": [...],
    ...: ...
}
```

So technically, this undocumented feature, supports stuff like this

```console
$ http --offline --print=B pie.dev/post [a]=1 [b]=2

{
    "": {
        "a": "1",
        "b": "2"
    }
}
```

And this

https://github.com/httpie/httpie/blob/86ba995ad881a1a09b04c8088211c40329932256/tests/test_json.py#L318-L325

There are 3 possible things we could do to resolve this:
- (1) Change it completely, don't allow top-level empty keys at all. Forbid usage of `[...]=something` syntax completely (where there is no key, unlike `a[...]=something`), unless `...` is an integer (or empty, since it would be append then).
- (2) Change it partially, what the initial issue suggests (forbid mixed operations).
- (3) Do nothing, since technically this is the correct behavior under the spec. **Not the most intutive one** though. 

I started to like **1**, it seem to match be consistent on the correctness aspect. But I fear the bad side might hit us, which there is no way to create empty top-level keys:
```console
$ http --offline --print=B pie.dev/post [a]=1 [b]=2

{
    "": {
        "a": "1",
        "b": "2"
    }
}
```

Unlike intermediary objects, which you could do this:

```
$ http --offline --print=B pie.dev/post a[b]:='{"": "x"}'

{
    "a": {
        "b": {
            "": "x"
        }
    }
}
```

**2** is alright, since it would solve the basic problem in the hand. But doesn't feel like a long term solution.

Leaving it as is doesn't seem very intutitve, so I'd say we should handle it one way or another.

---

I recall that we discussed this previously on a [discord thread](https://discord.com/channels/725351238698270761/801485021016752208/929057887685324821), but there weren't any resolution. I think reconsidering that example might make sense under this discussion.

**Comment by ducaale** [comment]
Thanks for explaining the current implementation.

>I started to like 1, it seem to match be consistent on the correctness aspect. But I fear the bad side might hit us, which there is no way to create empty top-level keys:

I think @jakubroztocil mentioned in the [same thread](https://discord.com/channels/725351238698270761/801485021016752208/930052488768393216) that it would still be possible to create empty top-level keys if the `[string]` syntax was banned:

>Actually, the key part of key/value items is optional, so you can just pass =aaa or :=1 and you’ll get an empty key:
> ```
> $ http --print=B --offline pie.dev/post :=1
>
> {
>    "": 1
> }
> ```
>
>Therefore, we don’t need the special [foo]=bar syntax for that.

**Comment by isidentical** [comment]
Ah, I have missed that. If we have a way like that, we can safely embed nested data directly `http --offline pie.dev/post ':={"foo": "bar"}'`. I think in the light of this, we can implement something similiar to your suggestion. @jakubroztocil WDYT?

```
start: (literal | index_path | append_path) path*
literal: TEXT | NUMBER
path:
     key_path
     | index_path  
     | append_path
```
