### ISSUE TITLE
More curl like verbosity

### ISSUE THREAD

**Issue by jungle-boogie** [httpie/httpie#329]
Hello Developers,

Could you please consider making httpie more like curl in terms of its verbosity?

httpie:
http://pastiebin.com/551182f6bec63

vs.

curl:
http://pastiebin.com/5511831e301ad

**Comment by Almad** [comment]
Let me break it down, what curl displays is:

* TLS details, see  #1011
* Connection information
* Request/response indicators (`>` and `<`)

For displaying the latter two, we need #1023 . The lasts breaks copy&paste ability, so that one needs product design. 

I am going to link to this issue in #1023, please let's move the discussion there.
