### ISSUE TITLE
Add 'quiet' or 'silent' option for using httpie in scripts

### ISSUE THREAD

**Issue by paulolieuthier** [httpie/httpie#926]
Simple flag to avoid unnecessary output when using inside scripts.

**Comment by jakubroztocil** [comment]
Rationale: [Why do many commands provide a “quiet” option?](https://unix.stackexchange.com/questions/191254/why-do-many-commands-provide-a-quiet-option)

We can handle this by replacing our `env.stdout` and `env.stderr` with `os.devnull` at the appropriate moment. Instead of touching `os.devnull` directly at runtime, though, it should be added as `Environment.devnull` like we do with the standard streams:

https://github.com/jakubroztocil/httpie/blob/492687b0dafb7bec0d6281d019bb5f4f60439346/httpie/context.py#L32-L35

…and only reference `env.devnull`. This will make it possible to write good tests.  So basically there should only be one conditional somewhere and all existing behavior should remain intact.

**Comment by paulolieuthier** [comment]
What should the flag be?

**Comment by jakubroztocil** [comment]
@paulolieuthier `--quiet`

**Comment by jakubroztocil** [comment]
The replacement should probably happen here:

https://github.com/jakubroztocil/httpie/blob/492687b0dafb7bec0d6281d019bb5f4f60439346/httpie/cli/argparser.py#L123-L154

**Comment by nb2838** [comment]
Hey! Is someone working on this issue or can it be taken?

**Comment by jakubroztocil** [comment]
@nb2838 I’m not so unless @paulolieuthier is looking into this it should be up for grabs.

**Comment by paulolieuthier** [comment]
Go ahead @nb2838! I'm looking forward to the release :)

**Comment by YKo20010** [comment]
@nb2838 Are you still working on this? I'd like to pick up this issue if not!

**Comment by nb2838** [comment]
Yes currently working on it :)

**Comment by nb2838** [comment]
I've been working on the problem and I think I have a working solution. My only problem thus far is that I don't know at which point precisely to close the os.devnull file.  If I don't close it and let the job be done by the garbage collectore my code works fine. However, when I try closing it by adding a 
`finally:
    env.dev.null.close()
`at the end of main in core.py I get an error if I use --download option. I was wondering if you have any suggestions for dealing with this issue.

**Comment by jakubroztocil** [comment]
@nb2838 please open a PR and I’ll take a look

**Comment by marcelo-r** [comment]
#945 was merged and closed.
