### ISSUE TITLE
Support header values read from file ?

### ISSUE THREAD

**Issue by coldcoff** [httpie/httpie#964]
httpie allows to get url params and form data from file, by using @ syntax

There are sometimes complicated headers, for example tokens.

It seems this is not yet possible for headers.

Can this feature be added for headers as well?

Probably with a syntax like:
```
':@'
```

like:

```
Referer:http://httpie.org  Cookie:foo=bar  User-Agent:bacon/1.0 FunnyHeader:@somefile
```

That would be very helpful.

**Comment by sharvanir** [comment]
can definitely give this a shot, @coldcoff may I trouble you for an example input file for this?

**Comment by coldcoff** [comment]
Yes, OK -- I will prepare some. Probably even more generic (multiple headers and their values in a file), thinking about it

**Comment by tikki** [comment]
Hi, I would also be interested in this feature. I'm using [curl's -H](https://curl.se/docs/manpage.html#-H) at the moment to safely include a secret bearer token in an HTTP request. As far as I know there's no better way to avoid leaking that information on the local machine (e.g. through `ps` or inspecting the shell env) and of course I'd like to be able to use httpie instead of curl. :)

For an example of what I do with curl:
```
$ cat example.auth-header
Authorization: Bearer secret-token:xyW1hLx2CCqS4w28DXHUz7yInOx9oE22aUCzWMslOioU24X6vtd1DsVBNInqmQqN
$ curl -H @example.auth-header http://api.example.com/v1/index
```

With the syntax as suggested by @sharvanir it would be
```
$ cat example.auth-header
Bearer secret-token:xyW1hLx2CCqS4w28DXHUz7yInOx9oE22aUCzWMslOioU24X6vtd1DsVBNInqmQqN
$ http http://api.example.com/v1/index Authorization:@example.auth-header
```
